apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Python
  generation: 2
  name: python
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Python 3.5 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/2.7/README.md.
      iconClass: icon-python
      openshift.io/display-name: Python 3.5
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/django-ex.git
      supports: python:3.5,python
      tags: builder,python
      version: "3.5"
    from:
      kind: DockerImage
      name: registry.redhat.io/rhscl/python-35-rhel7:latest
    generation: 2
    importPolicy: {}
    name: "3.5"
    referencePolicy:
      type: Local